#!/bin/bash
# installconfig: 199

source /etc/sysconfig/plugin_info
source $PLUGIN_CFG_DIR/w3serv.cfg
source $PLUGIN_CFG_DIR/dbcore
source $PLUGIN_CFG_DIR/lmsAgentPlugin.cfg

# Init Settings
MARKETPLACE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PLUGIN_NAME=marketplace
MARKETPLACE_SYSTEM_MANUFACTURER_CATALOGUE=panasonic
MARKETPLACE_SYSTEM_MANUFACTURER_PNR=panasonic
MARKETPLACE_SYSTEM_MANUFACTURER_FLIGHTINFORMATION=panasonic
MARKETPLACE_SYSTEM_MANUFACTURER_INVENTORY=panasonic
MARKETPLACE_SYSTEM_MANUFACTURER_SECURITY=panasonic
MARKETPLACE_CONFIG_FILE="${PLUGIN_CFG_DIR}/${PLUGIN_NAME}.cfg"
PLUGIN_LOG_DIR="${LOG_DIR}/${PLUGIN_NAME}"
MARKETPLACE_SOCK="/tmp/${PLUGIN_NAME}.sock"
MARKETPLACE_SHARED="${SHARE_DIR}/${PLUGIN_NAME}"
NGINX_CONF_DIR="${MARKETPLACE_SHARED}/nginx"
MARKETPLACE_LOCK_FILE=/var/lock/subsys/marketplace_server
MARKETPLACE_PID_FILE=/var/run/marketplace_server.pid
MARKETPLACE_DATA_DIR="${HOME}/${PLUGIN_NAME}"
MARKETPLACE_STORE_CONFIG_FILE="${MARKETPLACE_DATA_DIR}/${PLUGIN_NAME}_store_config.json"
MARKETPLACE_STAGE_DIR="${MARKETPLACE_DATA_DIR}/stage"
MARKETPLACE_CONFIG_OVERRIDE_FILE="${MARKETPLACE_DATA_DIR}/${PLUGIN_NAME}_overrides.cfg"
MARKETPLACE_SYSTEM_LOPADATA=$PLUGIN_CFG_DIR/cpdata.xml
MARKETPLACE_BASKET_RESERVE="reserve_on_validate"
MARKETPLACE_OFFLOAD_NEW="${MARKETPLACE_DATA_DIR}/offloads/new"
MARKETPLACE_OFFLOAD_FAILED="${MARKETPLACE_DATA_DIR}/offloads/failed"

# App Settings
MARKETPLACE_LOG_LEVEL="warn"
MARKETPLACE_LOG_FILE="${PLUGIN_LOG_DIR}/app.log"
MARKETPLACE_CONTENT_BASE_URL="http://bob-air.com/microsites/baw-catalogue-v1"
MARKETPLACE_CONTENT_DATA_URL="/project_media/catalogue/data/catalogue-data_signed.json"
MARKETPLACE_GROUND_INVENTORY_BASE_URL="https://master.marketplace-dev.nextcloud.aero/inventory"
MARKETPLACE_GROUND_PNR_BASE_URL="https://master.marketplace-dev.nextcloud.aero/nextflight/itinerary/nextflights"
MARKETPLACE_OFFLOAD_GROUND_BASE_URL="https://master.marketplace-dev.nextcloud.aero/orders/"
MARKETPLACE_SYSTEM_ICAO=`grep Airline_ICAO /etc/lru/lru.cfg | \
  sed -e "s/Airline_ICAO\s*=\s*//g" | \
  sed 's/[";]//g' | \
  awk '{print toupper($0)}'`

# Security Keys
# TODO: Swap out from KEYSTORE
MARKETPLACE_JWT_AUTH_SECRET="LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFtQ1R2bUNLUW5PNkZwc3FaQWNVUgpZcWcyTDU5cm45M0lOUmJKOW1vcVc0K000MkdaM2E3OGpEaUJGQjBnVEZIN2hEdmlEdGdmaUgzdVA5cDhVOVVKCjB3OVgrb3YwRGNZYnR4TlQ0cG1YQmZ5RnRKcHZtWDU5Lzh0U01hYXlQbVBkbEw3R1RkellBMllJWEFNaUJkcUoKWFpsUXM2dHZLQWpxSWMzSEN2TExqaU5GYlJGRUdCZmw3bVptdnZNU3BuSnFDQXBJSmZobjE5ZlA0Z09ra2xsTwp5Z0xxa3UrWkF6cysxOC96cW1udVNnWXVuRTlQbjZmYUt0dG5va05tRU9qQzQzTzdoSEVRYWRZWWpEa05OTC91CjRoZGVoakFFS2I1UUZ1RExERFJrNWVkdmxmT01CTlZDMnZ4K0J0aDBicGxrcmxqaDZXN1RDc3k1amFqa2dPS2sKblFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="

# Setup plugin for logging
mkdir -p $PLUGIN_LOG_DIR
LOG_FILE="${PLUGIN_LOG_DIR}/`basename $0`.log"

log()
{
    echo "(`date`): ${1}" >> $LOG_FILE
}

# MariaDB Settings
if [ -e ${PLUGIN_CFG_DIR}/dbcore ]; then
  ln -s ${MARKETPLACE_DIR}/conf.d/dbcore/marketplace_db.cfg ${DBCORE_REG_DIR}
  ln -s ${MARKETPLACE_DIR}/conf.d/dbcore/marketplace_db.create ${DBCORE_REG_DIR}
fi

log "%%% MARKETPLACE_DIR=${MARKETPLACE_DIR}"

log "=> Generating plugin config: ${MARKETPLACE_CONFIG_FILE}"
echo "MARKETPLACE_DIR=$MARKETPLACE_DIR" > $MARKETPLACE_CONFIG_FILE
echo "PLUGIN_NAME=${PLUGIN_NAME}" >> $MARKETPLACE_CONFIG_FILE
echo "PLUGIN_LOG_DIR=${PLUGIN_LOG_DIR}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_SOCK=${MARKETPLACE_SOCK}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_SHARED=${MARKETPLACE_SHARED}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_LOCK_FILE=${MARKETPLACE_LOCK_FILE}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_PID_FILE=${MARKETPLACE_PID_FILE}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_DATA_DIR=${MARKETPLACE_DATA_DIR}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_STORE_CONFIG_FILE=${MARKETPLACE_STORE_CONFIG_FILE}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_STAGE_DIR=${MARKETPLACE_STAGE_DIR}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_CONFIG_OVERRIDE_FILE=${MARKETPLACE_CONFIG_OVERRIDE_FILE}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_LOG_LEVEL=${MARKETPLACE_LOG_LEVEL}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_CONTENT_BASE_URL=${MARKETPLACE_CONTENT_BASE_URL}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_CONTENT_DATA_URL=${MARKETPLACE_CONTENT_DATA_URL}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_JWT_AUTH_SECRET=${MARKETPLACE_JWT_AUTH_SECRET}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_SYSTEM_MANUFACTURER_CATALOGUE=${MARKETPLACE_SYSTEM_MANUFACTURER_CATALOGUE}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_SYSTEM_MANUFACTURER_PNR=${MARKETPLACE_SYSTEM_MANUFACTURER_PNR}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_SYSTEM_MANUFACTURER_FLIGHTINFORMATION=${MARKETPLACE_SYSTEM_MANUFACTURER_FLIGHTINFORMATION}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_SYSTEM_MANUFACTURER_INVENTORY=${MARKETPLACE_SYSTEM_MANUFACTURER_INVENTORY}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_SYSTEM_MANUFACTURER_SECURITY=${MARKETPLACE_SYSTEM_MANUFACTURER_SECURITY}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_SYSTEM_ICAO=${MARKETPLACE_SYSTEM_ICAO}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_SYSTEM_LOPADATA=${MARKETPLACE_SYSTEM_LOPADATA}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_BASKET_RESERVE=${MARKETPLACE_BASKET_RESERVE}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_GROUND_INVENTORY_BASE_URL=${MARKETPLACE_GROUND_INVENTORY_BASE_URL}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_GROUND_PNR_BASE_URL=${MARKETPLACE_GROUND_PNR_BASE_URL}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_OFFLOAD_NEW=${MARKETPLACE_OFFLOAD_NEW}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_OFFLOAD_FAILED=${MARKETPLACE_OFFLOAD_FAILED}" >> $MARKETPLACE_CONFIG_FILE
echo "MARKETPLACE_OFFLOAD_GROUND_BASE_URL=${MARKETPLACE_OFFLOAD_GROUND_BASE_URL}" >> $MARKETPLACE_CONFIG_FILE

# Create shared disk folder
mkdir -p $MARKETPLACE_SHARED
mkdir -p $MARKETPLACE_DATA_DIR

# Create store config staging directory
mkdir -p $MARKETPLACE_STAGE_DIR

###
# START: NGINX Configs
###
#web confs
mkdir -p $NGINX_CONF_DIR
NGINX_TEMPLATE_DIR="${MARKETPLACE_DIR}/nginx_config_templates"

# Create nginx configs from templates
SEDEXP="-e s:__MARKETPLACE_SOCK__:${MARKETPLACE_SOCK}:g"
sed $SEDEXP "${NGINX_TEMPLATE_DIR}/marketplace_http.conf" > ${NGINX_CONF_DIR}/marketplace_http.conf
sed -i -e "s:__NGINX_CONF_DIR__:${NGINX_CONF_DIR}:g" "${NGINX_CONF_DIR}/marketplace_http.conf"
sed -i -e "s:__REAL_IP_INCLUDE_PATH__:${NGINX_CONF_DIR}/marketplace_trusted_proxy_ips.conf:g" "${NGINX_CONF_DIR}/marketplace_http.conf"

# Register each with VHost
$W3REGISTER_VHOST $NGINX_CONF_DIR/marketplace_http.conf http
log "Registered Nginx VHost: ${NGINX_CONF_DIR}/marketplace_http.conf"

###
# END: NGINX Configs
###

### Configure logrotate
if [ -n "${EDIT_LOGROTATE}" ]; then
	${EDIT_LOGROTATE} -r 4 -s 1024 ${PLUGIN_LOG_DIR}/app.log
	${EDIT_LOGROTATE} -r 4 -s 1024 ${PLUGIN_LOG_DIR}/app-process.std.log
	${EDIT_LOGROTATE} -r 4 -s 1024 ${PLUGIN_LOG_DIR}/app-process.err.log
fi

log "Register with Content Stage Handler"
$MARKETPLACE_DIR/bin/handlers/content_stage_handler.sh -r

MARKETPLACE_STORE_CONFIG_PN=`$LMS_DATA_QUERY -S MARKETPLACE_STORE_CONFIG -a pn -V | head -n 1`
if [ $? -eq 0 ] && [ -n "${MARKETPLACE_STORE_CONFIG_PN}" ]; then
    MARKETPLACE_STORE_CONFIG_VERSION=`$LMS_DATA_QUERY -S MARKETPLACE_STORE_CONFIG -a ver -V | head -n 1`
    log "MARKETPLACE_STORE_CONFIG is loaded";
    ${MARKETPLACE_DIR}/bin/content_stage_scripts/content-change-listener.sh -O install -P ${MARKETPLACE_STORE_CONFIG_PN} -V "${MARKETPLACE_STORE_CONFIG_VERSION}" -S MARKETPLACE_STORE_CONFIG
fi

MARKETPLACE_SYSTEM_CONFIG_PN=`$LMS_DATA_QUERY -S MARKETPLACE_SYSTEM_CONFIG -a pn -V | head -n 1`
if [ $? -eq 0 ] && [ -n "${MARKETPLACE_SYSTEM_CONFIG_PN}" ]; then
    MARKETPLACE_SYSTEM_CONFIG_VERSION=`$LMS_DATA_QUERY -S MARKETPLACE_SYSTEM_CONFIG -a ver -V | head -n 1`
    log "MARKETPLACE_STORE_CONFIG is loaded";
    ${MARKETPLACE_DIR}/bin/content_stage_scripts/content-change-listener.sh -O install -P ${MARKETPLACE_SYSTEM_CONFIG_PN} -V "${MARKETPLACE_SYSTEM_CONFIG_VERSION}" -S MARKETPLACE_SYSTEM_CONFIG
fi

# Trusted Proxy IPs
# source override environment to ensure all config overrides are applied
export `cat ${MARKETPLACE_CONFIG_OVERRIDE_FILE}`
(cd $MARKETPLACE_DIR && ${W3NODE8_CLI} bin/create-real-ip.js ${NGINX_CONF_DIR}/marketplace_trusted_proxy_ips.conf)

log "Completed"
